name: Deploy R1-D1

on:
  push:
    branches: [ main ] 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🛡️ Connexion au réseau Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci  # Doit correspondre au tag mis dans l'OAuth Client
          targets: ${{ secrets.SSH_HOST }} # Force l'attente du VPS
          
      - name: Connexion SSH et Mise à jour
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            # On utilise le bon chemin détecté sur ton VPS
            cd /opt/discordbot/vainebot || { echo "Dossier introuvable dans /opt"; exit 1; }
            
            # 1. On récupère le nouveau code
            git pull origin main
            
            # 2. On build la nouvelle image
            # Le '.' est crucial pour trouver le Dockerfile dans le dossier courant
            podman build -t vainebot .
            
            # 3. On redémarre le service
            systemctl --user daemon-reload
            systemctl --user restart container-vainebot.service
            
            # 4. On nettoie les images inutilisées
            podman image prune -f
